<?php if (!defined('ASSETS_FOLDER')) { define('ASSETS_FOLDER', './assets/'); } ?>
<div class="emoticons ess" style="background:#fff;">
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/1.gif" onclick="insertSmiley('[:1:]')" title="[:1:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/2.gif" onclick="insertSmiley('[:2:]')" title="[:2:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/3.gif" onclick="insertSmiley('[:3:]')" title="[:3:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/4.gif" onclick="insertSmiley('[:4:]')" title="[:4:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/5.gif" onclick="insertSmiley('[:5:]')" title="[:5:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/6.gif" onclick="insertSmiley('[:6:]')" title="[:6:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/7.gif" onclick="insertSmiley('[:7:]')" title="[:7:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/8.gif" onclick="insertSmiley('[:8:]')" title="[:8:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/9.gif" onclick="insertSmiley('[:9:]')" title="[:9:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/10.gif" onclick="insertSmiley('[:10:]')" title="[:10:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/11.gif" onclick="insertSmiley('[:11:]')" title="[:11:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/12.gif" onclick="insertSmiley('[:12:]')" title="[:12:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/13.gif" onclick="insertSmiley('[:13:]')" title="[:13:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/14.gif" onclick="insertSmiley('[:14:]')" title="[:14:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/15.gif" onclick="insertSmiley('[:15:]')" title="[:15:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/16.gif" onclick="insertSmiley('[:16:]')" title="[:16:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/17.gif" onclick="insertSmiley('[:17:]')" title="[:17:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/18.gif" onclick="insertSmiley('[:18:]')" title="[:18:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/19.gif" onclick="insertSmiley('[:19:]')" title="[:19:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/20.gif" onclick="insertSmiley('[:20:]')" title="[:20:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/21.gif" onclick="insertSmiley('[:21:]')" title="[:21:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/22.gif" onclick="insertSmiley('[:22:]')" title="[:22:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/23.gif" onclick="insertSmiley('[:23:]')" title="[:23:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/24.gif" onclick="insertSmiley('[:24:]')" title="[:24:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/25.gif" onclick="insertSmiley('[:25:]')" title="[:25:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/26.gif" onclick="insertSmiley('[:26:]')" title="[:26:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/27.gif" onclick="insertSmiley('[:27:]')" title="[:27:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/28.gif" onclick="insertSmiley('[:28:]')" title="[:28:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/29.gif" onclick="insertSmiley('[:29:]')" title="[:29:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/30.gif" onclick="insertSmiley('[:30:]')" title="[:30:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/31.gif" onclick="insertSmiley('[:31:]')" title="[:31:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/32.gif" onclick="insertSmiley('[:32:]')" title="[:32:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/33.gif" onclick="insertSmiley('[:33:]')" title="[:33:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/34.gif" onclick="insertSmiley('[:34:]')" title="[:34:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/35.gif" onclick="insertSmiley('[:35:]')" title="[:35:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/36.gif" onclick="insertSmiley('[:36:]')" title="[:36:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/37.gif" onclick="insertSmiley('[:37:]')" title="[:37:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/38.gif" onclick="insertSmiley('[:38:]')" title="[:38:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/39.gif" onclick="insertSmiley('[:39:]')" title="[:39:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/40.gif" onclick="insertSmiley('[:40:]')" title="[:40:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/41.gif" onclick="insertSmiley('[:41:]')" title="[:41:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/42.gif" onclick="insertSmiley('[:42:]')" title="[:42:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/43.gif" onclick="insertSmiley('[:43:]')" title="[:43:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/44.gif" onclick="insertSmiley('[:44:]')" title="[:44:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/45.gif" onclick="insertSmiley('[:45:]')" title="[:45:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/46.gif" onclick="insertSmiley('[:46:]')" title="[:46:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/47.gif" onclick="insertSmiley('[:47:]')" title="[:47:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/48.gif" onclick="insertSmiley('[:48:]')" title="[:48:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/49.gif" onclick="insertSmiley('[:49:]')" title="[:49:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/50.gif" onclick="insertSmiley('[:50:]')" title="[:50:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/51.gif" onclick="insertSmiley('[:51:]')" title="[:51:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/52.gif" onclick="insertSmiley('[:52:]')" title="[:52:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/53.gif" onclick="insertSmiley('[:53:]')" title="[:53:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/54.gif" onclick="insertSmiley('[:54:]')" title="[:54:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/55.gif" onclick="insertSmiley('[:55:]')" title="[:55:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/56.gif" onclick="insertSmiley('[:56:]')" title="[:56:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/57.gif" onclick="insertSmiley('[:57:]')" title="[:57:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/58.gif" onclick="insertSmiley('[:58:]')" title="[:58:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/59.gif" onclick="insertSmiley('[:59:]')" title="[:59:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/60.gif" onclick="insertSmiley('[:60:]')" title="[:60:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/61.gif" onclick="insertSmiley('[:61:]')" title="[:61:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/62.gif" onclick="insertSmiley('[:62:]')" title="[:62:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/63.gif" onclick="insertSmiley('[:63:]')" title="[:63:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/64.gif" onclick="insertSmiley('[:64:]')" title="[:64:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/65.gif" onclick="insertSmiley('[:65:]')" title="[:65:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/66.gif" onclick="insertSmiley('[:66:]')" title="[:66:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/tuzkiclub/67.gif" onclick="insertSmiley('[:67:]')" title="[:67:]" />
<div style="padding-top:10px;" class="muted">
<small>&copy; <a href="http://www.turnoutventures.com/" target="_blank">TurnOut Ventures Limited</a>, a joint venture between <a href="http://www.clubtuzki.com/" target="_blank">Turner Broadcasting System Asia Pasific, Inc.</a> and Outblaze Investments Limited</small>
</div>
</div>
<script>$(document).ready(function() { $('.emoticons img').tooltip(); });</script>