<?php if (!defined('ASSETS_FOLDER')) { define('ASSETS_FOLDER', './assets/'); } ?>
<div class="emoticons ess" style="background:#fff;">
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/blush.png" onclick="insertSmiley('[;blush;]')" title="[;blush;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/broken-heart.png" onclick="insertSmiley('[;broken-heart;]')" title="[;broken-heart;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/confuse.png" onclick="insertSmiley('[;confuse;]')" title="[;confuse;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/cool.png" onclick="insertSmiley('[;cool;]')" title="[;cool;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/cry.png" onclick="insertSmiley('[;cry;]')" title="[;cry;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/eek.png" onclick="insertSmiley('[;eek;]')" title="[;eek;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/evil.png" onclick="insertSmiley('[;evil;]')" title="[;evil;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/fat.png" onclick="insertSmiley('[;fat;]')" title="[;fat;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/green.png" onclick="insertSmiley('[;green;]')" title="[;green;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/grin.png" onclick="insertSmiley('[;grin;]')" title="[;grin;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/happy.png" onclick="insertSmiley('[;happy;]')" title="[;happy;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/heart.png" onclick="insertSmiley('[;heart;]')" title="[;heart;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/kiss.png" onclick="insertSmiley('[;kiss;]')" title="[;kiss;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/kitty.png" onclick="insertSmiley('[;kitty;]')" title="[;kitty;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/lol.png" onclick="insertSmiley('[;lol;]')" title="[;lol;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/mad.png" onclick="insertSmiley('[;mad;]')" title="[;mad;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/money.png" onclick="insertSmiley('[;money;]')" title="[;money;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/neutral.png" onclick="insertSmiley('[;neutral;]')" title="[;neutral;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/razz.png" onclick="insertSmiley('[;razz;]')" title="[;razz;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/roll.png" onclick="insertSmiley('[;roll;]')" title="[;roll;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/sad.png" onclick="insertSmiley('[;sad;]')" title="[;sad;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/sleep.png" onclick="insertSmiley('[;sleep;]')" title="[;sleep;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/surprise.png" onclick="insertSmiley('[;surprise;]')" title="[;surprise;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/wink.png" onclick="insertSmiley('[;wink;]')" title="[;wink;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/yell.png" onclick="insertSmiley('[;yell;]')" title="[;yell;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/zipper.png" onclick="insertSmiley('[;zipper;]')" title="[;zipper;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/like.png" onclick="insertSmiley('[;like;]')" title="[;like;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/dislike.png" onclick="insertSmiley('[;dislike;]')" title="[;dislike;]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/1.gif" onclick="insertSmiley('{;1;}')" title="{;1;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/2.gif" onclick="insertSmiley('{;2;}')" title="{;2;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/3.gif" onclick="insertSmiley('{;3;}')" title="{;3;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/4.gif" onclick="insertSmiley('{;4;}')" title="{;4;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/5.gif" onclick="insertSmiley('{;5;}')" title="{;5;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/6.gif" onclick="insertSmiley('{;6;}')" title="{;6;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/7.gif" onclick="insertSmiley('{;7;}')" title="{;7;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/8.gif" onclick="insertSmiley('{;8;}')" title="{;8;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/9.gif" onclick="insertSmiley('{;9;}')" title="{;9;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/10.gif" onclick="insertSmiley('{;10;}')" title="{;10;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/11.gif" onclick="insertSmiley('{;11;}')" title="{;11;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/12.gif" onclick="insertSmiley('{;12;}')" title="{;12;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/13.gif" onclick="insertSmiley('{;13;}')" title="{;13;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/14.gif" onclick="insertSmiley('{;14;}')" title="{;14;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/15.gif" onclick="insertSmiley('{;15;}')" title="{;15;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/16.gif" onclick="insertSmiley('{;16;}')" title="{;16;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/17.gif" onclick="insertSmiley('{;17;}')" title="{;17;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/18.gif" onclick="insertSmiley('{;18;}')" title="{;18;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/19.gif" onclick="insertSmiley('{;19;}')" title="{;19;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/20.gif" onclick="insertSmiley('{;20;}')" title="{;20;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/21.gif" onclick="insertSmiley('{;21;}')" title="{;21;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/22.gif" onclick="insertSmiley('{;22;}')" title="{;22;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/23.gif" onclick="insertSmiley('{;23;}')" title="{;23;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/24.gif" onclick="insertSmiley('{;24;}')" title="{;24;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/25.gif" onclick="insertSmiley('{;25;}')" title="{;25;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/26.gif" onclick="insertSmiley('{;26;}')" title="{;26;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/27.gif" onclick="insertSmiley('{;27;}')" title="{;27;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/28.gif" onclick="insertSmiley('{;28;}')" title="{;28;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/29.gif" onclick="insertSmiley('{;29;}')" title="{;29;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/30.gif" onclick="insertSmiley('{;30;}')" title="{;30;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/31.gif" onclick="insertSmiley('{;31;}')" title="{;31;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/32.gif" onclick="insertSmiley('{;32;}')" title="{;32;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/33.gif" onclick="insertSmiley('{;33;}')" title="{;33;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/34.gif" onclick="insertSmiley('{;34;}')" title="{;34;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/35.gif" onclick="insertSmiley('{;35;}')" title="{;35;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/36.gif" onclick="insertSmiley('{;36;}')" title="{;36;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/37.gif" onclick="insertSmiley('{;37;}')" title="{;37;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/38.gif" onclick="insertSmiley('{;38;}')" title="{;38;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/39.gif" onclick="insertSmiley('{;39;}')" title="{;39;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/40.gif" onclick="insertSmiley('{;40;}')" title="{;40;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/41.gif" onclick="insertSmiley('{;41;}')" title="{;41;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/42.gif" onclick="insertSmiley('{;42;}')" title="{;42;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/43.gif" onclick="insertSmiley('{;43;}')" title="{;43;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/44.gif" onclick="insertSmiley('{;44;}')" title="{;44;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/45.gif" onclick="insertSmiley('{;45;}')" title="{;45;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/46.gif" onclick="insertSmiley('{;46;}')" title="{;46;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/47.gif" onclick="insertSmiley('{;47;}')" title="{;47;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/48.gif" onclick="insertSmiley('{;48;}')" title="{;48;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/49.gif" onclick="insertSmiley('{;49;}')" title="{;49;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/50.gif" onclick="insertSmiley('{;50;}')" title="{;50;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/51.gif" onclick="insertSmiley('{;51;}')" title="{;51;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/52.gif" onclick="insertSmiley('{;52;}')" title="{;52;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/53.gif" onclick="insertSmiley('{;53;}')" title="{;53;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/54.gif" onclick="insertSmiley('{;54;}')" title="{;54;}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/55.gif" onclick="insertSmiley('{;55;}')" title="{;55;}" />
</div>
<script>$(document).ready(function() { $('.emoticons img').tooltip(); });</script>