<?php if (!defined('ASSETS_FOLDER')) { define('ASSETS_FOLDER', './assets/'); } ?>
<div class="emoticons ess" style="background:#fff;">
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/0.gif" onclick="insertSmiley('{:0:}')" title="{:0:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/1.gif" onclick="insertSmiley('{:1:}')" title="{:1:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/2.gif" onclick="insertSmiley('{:2:}')" title="{:2:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/3.gif" onclick="insertSmiley('{:3:}')" title="{:3:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/4.gif" onclick="insertSmiley('{:4:}')" title="{:4:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/5.gif" onclick="insertSmiley('{:5:}')" title="{:5:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/6.gif" onclick="insertSmiley('{:6:}')" title="{:6:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/7.gif" onclick="insertSmiley('{:7:}')" title="{:7:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/8.gif" onclick="insertSmiley('{:8:}')" title="{:8:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/9.gif" onclick="insertSmiley('{:9:}')" title="{:9:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/10.gif" onclick="insertSmiley('{:10:}')" title="{:10:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/11.gif" onclick="insertSmiley('{:11:}')" title="{:11:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/12.gif" onclick="insertSmiley('{:12:}')" title="{:12:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/13.gif" onclick="insertSmiley('{:13:}')" title="{:13:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/14.gif" onclick="insertSmiley('{:14:}')" title="{:14:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/15.gif" onclick="insertSmiley('{:15:}')" title="{:15:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/16.gif" onclick="insertSmiley('{:16:}')" title="{:16:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/17.gif" onclick="insertSmiley('{:17:}')" title="{:17:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/18.gif" onclick="insertSmiley('{:18:}')" title="{:18:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/19.gif" onclick="insertSmiley('{:19:}')" title="{:19:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/20.gif" onclick="insertSmiley('{:20:}')" title="{:20:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/21.gif" onclick="insertSmiley('{:21:}')" title="{:21:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/22.gif" onclick="insertSmiley('{:22:}')" title="{:22:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/23.gif" onclick="insertSmiley('{:23:}')" title="{:23:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/24.gif" onclick="insertSmiley('{:24:}')" title="{:24:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/25.gif" onclick="insertSmiley('{:25:}')" title="{:25:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/26.gif" onclick="insertSmiley('{:26:}')" title="{:26:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/27.gif" onclick="insertSmiley('{:27:}')" title="{:27:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/28.gif" onclick="insertSmiley('{:28:}')" title="{:28:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/29.gif" onclick="insertSmiley('{:29:}')" title="{:29:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/30.gif" onclick="insertSmiley('{:30:}')" title="{:30:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/31.gif" onclick="insertSmiley('{:31:}')" title="{:31:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/32.gif" onclick="insertSmiley('{:32:}')" title="{:32:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/33.gif" onclick="insertSmiley('{:33:}')" title="{:33:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/34.gif" onclick="insertSmiley('{:34:}')" title="{:34:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/35.gif" onclick="insertSmiley('{:35:}')" title="{:35:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/36.gif" onclick="insertSmiley('{:36:}')" title="{:36:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/37.gif" onclick="insertSmiley('{:37:}')" title="{:37:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/38.gif" onclick="insertSmiley('{:38:}')" title="{:38:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/39.gif" onclick="insertSmiley('{:39:}')" title="{:39:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/40.gif" onclick="insertSmiley('{:40:}')" title="{:40:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/41.gif" onclick="insertSmiley('{:41:}')" title="{:41:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/42.gif" onclick="insertSmiley('{:42:}')" title="{:42:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/43.gif" onclick="insertSmiley('{:43:}')" title="{:43:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/44.gif" onclick="insertSmiley('{:44:}')" title="{:44:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/45.gif" onclick="insertSmiley('{:45:}')" title="{:45:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/46.gif" onclick="insertSmiley('{:46:}')" title="{:46:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/47.gif" onclick="insertSmiley('{:47:}')" title="{:47:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/48.gif" onclick="insertSmiley('{:48:}')" title="{:48:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/49.gif" onclick="insertSmiley('{:49:}')" title="{:49:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/51.gif" onclick="insertSmiley('{:51:}')" title="{:51:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/52.gif" onclick="insertSmiley('{:52:}')" title="{:52:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/53.gif" onclick="insertSmiley('{:53:}')" title="{:53:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/54.gif" onclick="insertSmiley('{:54:}')" title="{:54:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/55.gif" onclick="insertSmiley('{:55:}')" title="{:55:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/56.gif" onclick="insertSmiley('{:56:}')" title="{:56:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/57.gif" onclick="insertSmiley('{:57:}')" title="{:57:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/58.gif" onclick="insertSmiley('{:58:}')" title="{:58:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/59.gif" onclick="insertSmiley('{:59:}')" title="{:59:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/60.gif" onclick="insertSmiley('{:60:}')" title="{:60:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/61.gif" onclick="insertSmiley('{:61:}')" title="{:61:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/62.gif" onclick="insertSmiley('{:62:}')" title="{:62:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/63.gif" onclick="insertSmiley('{:63:}')" title="{:63:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/64.gif" onclick="insertSmiley('{:64:}')" title="{:64:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/65.gif" onclick="insertSmiley('{:65:}')" title="{:65:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/66.gif" onclick="insertSmiley('{:66:}')" title="{:66:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/67.gif" onclick="insertSmiley('{:67:}')" title="{:67:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/68.gif" onclick="insertSmiley('{:68:}')" title="{:68:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/69.gif" onclick="insertSmiley('{:69:}')" title="{:69:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/70.gif" onclick="insertSmiley('{:70:}')" title="{:70:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/71.gif" onclick="insertSmiley('{:71:}')" title="{:71:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/72.gif" onclick="insertSmiley('{:72:}')" title="{:72:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/73.gif" onclick="insertSmiley('{:73:}')" title="{:73:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/74.gif" onclick="insertSmiley('{:74:}')" title="{:74:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/75.gif" onclick="insertSmiley('{:75:}')" title="{:75:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/76.gif" onclick="insertSmiley('{:76:}')" title="{:76:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/77.gif" onclick="insertSmiley('{:77:}')" title="{:77:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/78.gif" onclick="insertSmiley('{:78:}')" title="{:78:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/79.gif" onclick="insertSmiley('{:79:}')" title="{:79:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/80.gif" onclick="insertSmiley('{:80:}')" title="{:80:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/81.gif" onclick="insertSmiley('{:81:}')" title="{:81:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/82.gif" onclick="insertSmiley('{:82:}')" title="{:82:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/83.gif" onclick="insertSmiley('{:83:}')" title="{:83:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/84.gif" onclick="insertSmiley('{:84:}')" title="{:84:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/85.gif" onclick="insertSmiley('{:85:}')" title="{:85:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/86.gif" onclick="insertSmiley('{:86:}')" title="{:86:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/87.gif" onclick="insertSmiley('{:87:}')" title="{:87:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/88.gif" onclick="insertSmiley('{:88:}')" title="{:88:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/89.gif" onclick="insertSmiley('{:89:}')" title="{:89:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/90.gif" onclick="insertSmiley('{:90:}')" title="{:90:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/91.gif" onclick="insertSmiley('{:91:}')" title="{:91:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/92.gif" onclick="insertSmiley('{:92:}')" title="{:92:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/93.gif" onclick="insertSmiley('{:93:}')" title="{:93:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/94.gif" onclick="insertSmiley('{:94:}')" title="{:94:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/95.gif" onclick="insertSmiley('{:95:}')" title="{:95:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/96.gif" onclick="insertSmiley('{:96:}')" title="{:96:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/97.gif" onclick="insertSmiley('{:97:}')" title="{:97:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/98.gif" onclick="insertSmiley('{:98:}')" title="{:98:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/99.gif" onclick="insertSmiley('{:99:}')" title="{:99:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/100.gif" onclick="insertSmiley('{:100:}')" title="{:100:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/101.gif" onclick="insertSmiley('{:101:}')" title="{:101:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/102.gif" onclick="insertSmiley('{:102:}')" title="{:102:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/103.gif" onclick="insertSmiley('{:103:}')" title="{:103:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/104.gif" onclick="insertSmiley('{:104:}')" title="{:104:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/105.gif" onclick="insertSmiley('{:105:}')" title="{:105:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/106.gif" onclick="insertSmiley('{:106:}')" title="{:106:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/107.gif" onclick="insertSmiley('{:107:}')" title="{:107:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/108.gif" onclick="insertSmiley('{:108:}')" title="{:108:}" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/109.gif" onclick="insertSmiley('{:109:}')" title="{:109:}" />
<div style="padding-top:10px;" class="muted">
<small>&copy; Ethan Liu (Taiwanese artist) at emstudio under <a href="http://creativecommons.org/licenses/by/3.0/" target="_blank">CC BY 3.0</a></small>
</div>
</div>
<script>$(document).ready(function() { $('.emoticons img').tooltip(); });</script>